module.exports = Object.freeze({
  APP_NAME: "easySWAT",

  APP_NAME: "AmlFileUploader",

  DASHBOARD: "Dashboard",
  DASHBOARD_LINK: "/amf-file-uploader/dashboard",
  TRACK_DASHBOARD_LINK: "/amf-file-uploader/track-dashboard",
  INCIDENT_DASHBOARD_LINK: "/amf-file-uploader/incident-dashboard",
  RECOMMENDATION_DASHBOARD_LINK: "/amf-file-uploader/recommendation-dashboard",

  UPLOADER: "File Uploader",
  UPLOADER_LINK: "/amf-file-uploader/uploader",

  RAISE_MOD_ALERT: "Raise Alarm",
  RAISE_MOD_ALERT_LINK: "/amf-file-uploader/raise-alert",

  STOP_MOD_ALERT: "Stop Alarm",
  STOP_MOD_ALERT_LINK: "/amf-file-uploader/stop-alert",

  RAISE_ALERT_HEADER: "Issue Details",

  MOD_ALERT_PAGE_LINK: "/amf-file-uploader/mod-alert-info",

  LOGIN_LINK: "/amf-file-uploader/login",

  LOGOUT: "Logout",
  LOGOUT_LINK: "/logout",

  CHANGE_PASSWORD: "Change Password",
  CHANGE_PASSWORD_LINK: "/amf-file-uploader/user/change-password",

  FORGOT_PASSWORD: "Forget Password",
  FORGOT_PASSWORD_LINK:  "/amf-file-uploader/forgot-password",

  MY_PROFILE: "User Profile",
  MY_PROFILE_LINK: "/amf-file-uploader/user/user-profile",

  SETTINGS: "Settings",
  SETTINGS_LINK: "/amf-file-uploader/profile/app-settings",

  SUPPORT: "Support",
  SUPPORT_LINK: "/amf-file-uploader/user/support",

  HELP: "Help",
  HELP_LINK: "",

  LICENSE_INFO: "License Info",
  LICENSE_INFO_LINK: "",

  ONBOARDING: "Onboarding",

  CLIENT: "Client",
  ONBOARD_CLIENT: "Onboard Client",
  ONBOARD_CLIENT_LINK: "/amf-file-uploader/client/onboard-client",

  PROJECT: "Project",
  ONBOARD_PROJECT: "Onboard Project",
  ONBOARD_PROJECT_LINK: "/amf-file-uploader/project/onboard-project",

  DWN_STREAM_APPLICATION: "Downstream Application",
  ONBOARD_DWN_STREAM_APP: "Onboard Downstream App",
  ONBOARD_DWN_STREAM_APP_LINK: "/amf-file-uploader/app/onboard-dwn-stream-app",
  DWN_STREAM_APP_LIST: "Onboarded Downstream Applications",

  APPLICATION: "Application",
  ONBOARD_APP: "Onboard App",
  ONBOARD_APP_LINK: "/amf-file-uploader/app/onboard-app",
  APP_LIST: "Onboarded Applications",
  INVENTORY_DETAILS: "Inventory Details",
  TECH_AND_DEV_STACK: "Tech & Dev Stack",

  TRACK: "Track",
  ONBOARD_TRACK: "Onboard Track",
  ONBOARD_TRACK_LINK: "/amf-file-uploader/track/onboard-track",

  COMPONENT_LIST: "Onboarded Components",
  COMPONENT: "Component",
  ONBOARD_COMPONENT: "Onboard Component",
  ONBOARD_COMPONENT_LINK: "/amf-file-uploader/track/onboard-component",

  USER: "User",

  RESOURCE: "Resource",
  ONBOARD_RESOURCE: "Onboard Resource",
  ONBOARD_RESOURCE_LINK: "/amf-file-uploader/resource/onboard-resource",

  DEPLOY_RESOURCE: "Deploy Resource",
  DEPLOY_RESOURCE_LINK: "/amf-file-uploader/resource/deploy-resource",

  ONBOARD_USER: "Onboard User",
  ONBOARD_USER_LINK: "/amf-file-uploader/user/onboard-user",

  MOM: "MOM",
  ADD_MOM: "Add MOM",
  MOM_LINK: "/amf-file-uploader/mom",
  MOM_LIST_URL: "momMicroService/momManagementService/getMomList",

  INCIDENT_MGMT: "Incident Mgmt",
  CREATE_INCIDENT: "Add Incident",
  UPDATE_INCIDENT: "Update Incident",
  CREATE_INCIDENT_LINK: "/amf-file-uploader/incident-management",
  UPDATE_INCIDENT: "Update Incident",
  UPDATE_INCIDENT_LINK: "/amf-file-uploader/update-incident",
  VIEW_INCIDENT: "View Incident",
  VIEW_INCIDENTS_LINK: "/amf-file-uploader/incident-list",
  APPROVE_INCIDENT: "Approve Incident",
  APPROVE_INCIDENT_LINK: "/amf-file-uploader/approve-incident",

  ADD_INCIDENT_EVENT: "Add Incident Event",
  ADD_INCIDENT_EVENT_LINK: "/amf-file-uploader/add-event",

  ADD_INCIDENT_ANALYSIS: "Add Incident Analysis",
  ADD_INCIDENT_ANALYSIS_LINK: "/amf-file-uploader/add-Analysis",

  PAS_GUIDELINES: "PAS Guidelines",
  ADD_PAS_GUIDELINES: "Add PAS Guidelines",
  ADD_PAS_GUIDELINES_LINK: "/amf-file-uploader/add-pas-guidelines",
  VIEW_PAS_GUIDELINES: "View PAS Guidelines",
  VIEW_PAS_GUIDELINES_LINK: "/amf-file-uploader/view-pas-guidelines",
  PUBLISH_PAS_GUIDELINES: "Publish PAS Guidelines",
  PUBLISH_PAS_GUIDELINES_LINK: "/amf-file-uploader/publish-pas-guidelines",

  RECOMMENDATIONS: "Recommendations",
  ADD_RECOMMENDATIONS: "Add Recommendation",
  ADD_RECOMMENDATIONS_LINK: "/amf-file-uploader/add-recommendations",
  UPDATE_RECOMMENDATIONS: "Update Recommendation",
  UPDATE_RECOMMENDATIONS_LINK: "/amf-file-uploader/update-recommendations",
  RECOMMENDATIONS_LISTS: "Recommendation_Lists",
  VIEW_RECOMMENDATIONS_LINK: "/amf-file-uploader/view-recommendations",
  DELETE_RECOMMENDATIONS_LINK: "/amf-file-uploader/delete-recommendations",
  PUBLISH_RECOMMENDATIONS_LINK: "/amf-file-uploader/publish-recommendations",

  PATCH_RELEASE: "Patch Release",
  RELEASE_DETAILS: "Release Details",
  RELEASE_QUESTION: "Release Question",

  REPORTS: "Reports",
  DEGRADED_REPORT: "Degraded Report",
  ISSUES_REPORT: "Issues Report",

  RECOMMENDATION: "Recommendation",
  ADD_RECMMND: "Add Recommendation",
  UPDATE_RECMMND: "Update Recommendation",
  RECOMMENDATIONS_LIST: "View Recommendation",
  // RECOMMENDATIONS_REPORT: "Report",

  TASK: "Task",
  ADD_TASK: "Add Task",
  ASSIGN_TASK: "Assign Task",
  TASK_REPORT: "Task Reports",

  TOOLS: "Tools",
  CAPACITY_PLANNER: "Capacity Planner",
  BULK_AWR_PARSER: "Bulk AWR Parser",
  CODE_REVIEW: "Code Review",
  SYSTEM_TRACER: "System Tracer",
  THREAD_DUMP_ANALYSER: "Thread Dump Analyser",
  HEAP_DUMP_ANALYSER: "Heap Dump Analyser",
  GC_LOGS_ANALYSER: "GC Logs Analyser",
  LOGS_ANALYSER: "Logs Analyser",

  BASE_URL: "http://127.0.0.1:8080/",
  COMMON_MODULE_BASE_URL: "http://192.168.0.236:9090/common-module/",
  ONBOARD_MODULE_BASE_URL: "http://127.0.0.1:9091/onboard-module/",
  INCIDENT_MGM_BASE_URL: "http://127.0.0.1:9094/incident-module/",
  RECOMMENDATION_BASE_URL: "http://127.0.0.1:9095/recommendation-module/",
  RAISE_ALARM_BASE_URL: "http://127.0.0.1:9096/easyswatnotification/",

  // Prod Changes Required
  // BASE_URL: 'http://34.222.198.118:8080/',
  // COMMON_MODULE_BASE_URL: 'http://34.222.198.118:9090/common-module/',
  // ONBOARD_MODULE_BASE_URL: 'http://34.222.198.118:9091/onboard-module/',
  // INCIDENT_MGM_BASE_URL: 'http://34.222.198.118:9094/incident-module/',
  // RECOMMENDATION_BASE_URL: 'http://34.222.198.118:9095/recommendation-module/',
  // RAISE_ALARM_BASE_URL: 'http://34.222.198.118:9096/easyswatnotification/',

  SETTINGS_URL: "setting-service/settings",
  DROPDOWN_LIST_URL: "masterService/dropDownData",
  TEAM_DROPDOWN_LIST_URL: "masterService/teamDropDownData",
  RECOMMENDATION_DROPDOWN_URL: "masterService/recommnedationDDData",
  APP_DROPDOWN_URL: "masterService/getAppList",
  MANAGER_LIST: "masterService/manager-list",
  DESIGNATION_LIST_URL: "common/designation-list",
  USER_LOGIN_URL: "auth/user-login",
  CHANGE_PASSWORD_URL: "auth/changePassword",
  USER_PROFILE_URL: "masterService/getProfileData",
  
  SUPPORT_TICKET_LIST_URL: "support/ticketList",
  SUPPORT_CREATE_TICKET_URL: "support/createTicket",
  SUPPORT_UPDATE_TICKET_URL: "support/updateTicket",
  SUPPORT_DELETE_TICKET_URL: "support/deleteTicket",

  ONBOARD_DWN_STRM_APP_URL: "dsAppMasterService/onboardDwnStreamApp",
  UPDATE_DWN_STRM_APP_URL: "dsAppMasterService/updateDwnStreamApp",
  DELETE_DWN_STRM_APP_URL: "dsAppMasterService/deleteDwnStreamApp",
  GET_DWN_STRM_APPLIST_URL: "dsAppMasterService/dwnStrmAppData",
  GET_DWN_STRM_APPLIST_FOR_APP_URL: "dsAppMasterService/dwnStrmAppForApp",

  ONBOARD_APP_URL: "appMasterService/onboardApp",
  UPDATE_APP_URL: "appMasterService/updateApp",
  DELETE_APP_URL: "appMasterService/deleteApp",
  GET_APPLIST_URL: "appMasterService/appDataList",
  CLNT_PRJCT_BASED_APP_NAME_LIST_URL: "appMasterService/client-project-based-app-name-list",
  APP_NAME_LIST_WITH_TRACK_COUNT_URL: "appMasterService/app-name-list-with-track-count",
  GET_DASHBOARD_APP_LIST_URL: "appMasterService/get-dashboard-app-list",

  GET_COMPONENT_PRELOADS_URL: "masterService/tool-master-list",
  GET_COMPONENTLIST_URL: "onboard-component/get-component-list",
  ADD_COMPONENT_URL: "onboard-component/add-component",
  UPDATE_COMPONENT: "onboard-component/update-component",
  DELETE_COMPONENT: "onboard-component/delete-component",
  GET_COMPONENT_LIST: "onboard-component/component-name-list",
  APP_BASED_COMPONENT_NAME_LIST_URL: "masterService/app-based-component-name-list",

  ONBOARD_CLIENT_URL: "onboard-client/add-client",
  UPDATE_CLIENT_URL: "onboard-client/update-client",
  DELETE_CLIENT_URL: "onboard-client/delete-client",
  CLIENT_LIST_URL: "onboard-client/client-list",
  CLIENT_NAME_LIST_URL: "onboard-client/client-name-list",
  CLIENT_NAME_LIST_WITH_PRO_COUNT_URL: "onboard-client/client-name-list-with-pro-count",

  ONBOARD_PROJECT_URL: "onboard-project/add-project",
  UPDATE_PROJECT_URL: "onboard-project/update-project",
  DELETE_PROJECT_URL: "onboard-project/delete-project",
  PROJECT_LIST_URL: "onboard-project/project-list",
  CLIENT_BASED_PROJECT_NAME_LIST_URL: "onboard-project/client-based-project-name-list",
  PROJECT_NAME_LIST_WITH_APP_COUNT_URL: "onboard-project/project-name-list-with-app-count",
  CLT_NAME_PROJECT_NAME_LIST_WITH_APP_COUNT_URL: "onboard-project/client-name-project-name-list-with-app-count",

  ONBOARD_TRACK_URL: "onboard-track/add-track",
  UPDATE_TRACK_URL: "onboard-track/update-track",
  DELETE_TRACK_URL: "onboard-track/delete-track",
  TRACK_LIST_URL: "onboard-track/track-list",
  DASHBOARD_BUTTON_VALUES_URL: "onboard-track/dashboard-button-values",
  APP_LEVEL_TRACK_LIST_URL: "onboard-track/app-level-track-list",
  TRACK_BASED_APP_LIST: "onboard-track/get-swat-app-list",
  APP_BASED_TRACK_NAME_LIST_URL: "onboard-track/app-based-track-name-list",
  GET_TRACK_DETAILS_BASEDON_ID_URL: "onboard-track/get-track-details-basedon-id",
  GET_NAME_BASED_TRACK_LIST_URL: "onboard-track/get-name-based-track-list",

  CREATE_INCIDENT_URL: "incident-service/add-incident",
  VIEW_INCIDENT_URL: "incident-service/view-incident",
  DELETE_INCIDENT_URL: "incident-service/delete-incident",
  EDIT_INCIDENT_URL: "incident-service/edit-incident",
  UPDATE_INCIDENT_URL: "incident-service/update-incident",
  UPDATE_INCIDENT_FROM_MOD_URL: "incident-service/update-incident-mod",
  INCIDENT_AUDIT_INCIDENT_URL: "incident-service/get-event-history",
  INCIDENT_ID_LIST_URL: "incident-service/incident-id-list",
  INCIDENT_AUDIT_EVENTS_URL: "incident-service/incident-events",
  NEW_INCIDENT_ID_URL: "incident-service/new-incident-id",
  APP_TRACK_BASED_INCIDENT_LIST_URL: "incident-service/app-track-based-incident-list",
  APP_TRACK_STATUS_BASED_INCIDENT_LIST_URL: "incident-service/app-track-status-based-incident-list",
  INCIDENT_CURRENT_STATUS_COUNT_URL: "incident-service/current-status-count",
  INCIDENT_CURRENT_STATUS_COUNT_LIST_URL: "incident-service/current-status-count-list",
  INCIDENT_DETAILS_ID_BASED_URL: "incident-service/incident-details-id-based",
  COMPONENT_LEVEL_EVENT_ANALYSIS_DETAILS_URL: "incident-service/component-level-event-analysis-details",
  APPLICATION_LEVEL_EVENT_ANALYSIS_DETAILS_URL: "incident-service/application-level-event-analysis-details",
  GET_INCIDENT_ARTIFACTS_IMAGE_BASE64_URL: "incident-service/get-artifacts-image-base64",
  GET_INCIDENT_CREATED_DETAILS_URL: "incident-service/get-incident-created-details",
  IMPORT_INCIDENT_DETAILS_URL: "incident-service/importIncidentDetails",
  GET_TRACK_NAME_BASED_INCIDENT_LIST_URL: "incident-service/get-track-name-based-incident-list",

  RCA_APPROVER_LIST_URL: "masterService/rca-checker-list",

  ADD_INCIDENT_EVENT_URL: "incident-event-service/add-incident-event",
  UPDATE_INCIDENT_EVENT_URL: "incident-event-service/update-incident-event",
  DELETE_INCIDENT_EVENT_URL: "incident-event-service/delete-incident-event",
  VIEW_INCIDENT_EVENT_URL: "incident-event-service/incident-event-list",
  INCIDENT_BASED_INCIDENT_EVENT_LIST_URL: "incident-event-service/incident-based-incident-event-list",
  GET_INCIDENT_EVENT_ARTIFACTS_IMAGE_BASE64_URL: "incident-event-service/get-artifacts-image-base64",
  GET_EVENT_TIMELINE_REPORT_DETAILS_URL: "incident-event-service/get-timeline-report-details",

  ADD_INCIDENT_ANALYSIS_URL: "incident-analysis-service/add-incident-analysis",
  UPDATE_INCIDENT_ANALYSIS_URL: "incident-analysis-service/update-incident-analysis",
  DELETE_INCIDENT_ANALYSIS_URL: "incident-analysis-service/delete-incident-analysis",
  VIEW_INCIDENT_ANALYSIS_URL: "incident-analysis-service/incident-analysis-list",
  INCIDENT_BASED_INCIDENT_ANALYSIS_LIST_URL: "incident-analysis-service/incident-based-incident-analysis-list",
  GET_INCIDENT_ANALYSIS_ARTIFACTS_IMAGE_BASE64_URL: "incident-analysis-service/get-artifacts-image-base64",
  GET_ANALYSIS_TIMELINE_REPORT_DETAILS_URL: "incident-analysis-service/get-timeline-report-details",

  ADD_PAS_GUIDELINES_URL: "pas-service/add-pas-guidelines",
  UPDATE_PAS_GUIDELINES_URL: "pas-service/update-pas-guidelines",
  PAS_GUIDELINES_LIST_URL: "pas-service/pas-guidelines-list",
  DELETE_PAS_GUIDELINES_URL: "pas-service/delete-pas-guidelines",
  IMPORT_PAS_GUIDLINES_URL: "pas-service/import-pas-guidlines",
  GET_PAS_GUIDELINES_LIST_BASED_ID_LIST: "pas-service/get-pas-guidelines-list-based-id-list",
  GET_MITIGATION_COMPONENT_COUNTS_URL: "pas-service/get-mitigation-component-counts",

  ACCOUNT_MANAGER_NAME_LIST_URL: "onboard-resource-service/account-manager-name-list",
  PROJECT_MANAGER_NAME_LIST_URL: "onboard-resource-service/project-manager-name-list",

  ONBOARD_RESOURCE_URL: "onboard-resource-service/add-resource",
  UPDATE_RESOURCE_URL: "onboard-resource-service/update-resource",
  ONBOARDED_RESOURCE_LIST_URL: "onboard-resource-service/resources-list",
  DELETE_ONBOARDED_RESOURCE_URL: "onboard-resource-service/delete-resource",
  RESOURCE_NAME_LIST_URL: "onboard-resource-service/resources-name-list",

  ONBOARD_USER_URL: "onboard-user-service/add-user",
  ONBOARDED_USER_LIST_URL: "onboard-user-service/user-list",
  UPDATE_ONBOARDED_USER_URL: "onboard-user-service/update-user",
  DELETE_ONBOARDED_USER_URL: "onboard-user-service/delete-user",

  ADD_RECOMMENDATION: "recommendationService/add-recommendation",
  UPDATE_RECOMMENDATION: "recommendationService/update-recommendation",
  DELETE_RECOMMENDATION: "recommendationService/delete-recommendation",
  GET_RECOMMENDATION_URL: "recommendationService/get-recommendation-list",
  GET_RECOMM_ON_ID_URL: "recommendationService/get-recommendation-details",
  GET_ALL_RECOMM_URL: "recommendationService/get-all-recommendation-details",
  GET_RECOMM_EVENT_HISTORY_LIST_URL: "recommendationService/get-event-history",
  GET_RECOMM_LIST_BASED_ID_LIST_URL: "recommendationService/get-recom-list-based-id-list",
  APP_TRACK_LEVEL_RECOMMENDATION_LIST_URL: "recommendationService/app-track-level-recommendation-list",
  APP_TRACK_STATUS_LEVEL_RECOMMENDATION_LIST_URL: "recommendationService/app-track-status-level-recommendation-list",
  RECOMMENDATION_CURRENT_STATUS_COUNT_URL: "recommendationService/current-status-count",
  RECOMMENDATION_CURRENT_STATUS_COUNT_LIST_URL: "recommendationService/current-status-count-list",
  GET_RECOMMEND_ARTIFACTS_IMAGE_BASE64_URL: "recommendationService/get-artifacts-image-base64",
  GET_TRACK_NAME_BASED_RECOMMEND_LIST_URL: "recommendationService/get-track-name-based-recommendation-list",

  IMPORT_RECOMMENDATION_DETAILS_URL: "recommendationService/importRecommendations",
  EXPORT_RECOMMENDATION_DETAILS_URL: "recommendationService/exportRecommendations",

  GET_MOD_ALERTS: "sendmessage/get-mod-alerts",
  RAISE_ALARM_URL: "sendmessage/raise-alarm",
  STOP_ALARM_URL: "sendmessage/stop-alarm",
  GET_ALL_MOD_ALARM_LIST_URL: "sendmessage/get-all-mod-alarm-list",
  GET_DATE_BASED_MOD_ALARM_LIST_URL: "sendmessage/get-date-based-mod-alarm-list",
  GET_DASHBOARD_MOD_ALARMS_CHART_URL: "sendmessage/get-dashboard-mond-alarms-chart",

  //Publish Url's
  PUBLISH_INCIDENT_DETAILS_URL: "mail-service/publish-incident-details",
  PUBLISH_RECOMMENDATION_DETAILS_URL: "mail-service/publish-recommendation-details",
  PUBLISH_ONBOARD_RESOURCE_DETAILS_URL: "mail-service/publish-onboard-resource",
  PUBLISH_ONBOARD_USER_DETAILS_URL: "mail-service/publish-onboard-user",
  PUBLISH_DEPLOY_RESOURCE_DETAILS_URL: "mail-service/publish-deploy-resource",
  PUBLISH_ONBOARD_COMPONENT_DETAILS_URL: "mail-service/publish-onboard-component",
  PUBLISH_CONSOILDATE_RECOMMENDATIONS_URL: "mail-service/publish-consolidate-recommendations",

  //Deploy Resource
  DEPLOY_RESOURCE_URL: "deployment-service/deploy-reource",
  DEPLOYED_RESOURCE_LIST_URL: "deployment-service/deployed-resources-list",
  DELETE_DEPLOYED_RESOURCE_URL: "deployment-service/delete-deployed-resource",
  UPDATE_DEPLOYED_RESOURCE_URL: "deployment-service/update-deployed-resource",
  GET_TRACK_BASED_DEPLOYED_RESOURCE_LIST_URL: "deployment-service/get-track-based-deployed-resource-list",
  PROJ_BASED_TRACK_NAME_LIST_URL: "onboard-track/proj-based-track-name-list",

  // File Uploader

  VALIDATE_LICENSE : "masterService/checklicense",
  SFTP_CREATE_CONNECTION : "api/create-connection",
  SFTP_UPLOAD_STATUS : "api/upload-status",
  SFTP_FILE_DOWNLOAD : "api/download",
  SFTP_REMOTE_DIRECTORY : "api/sftp-directory-contents",
  SFTP_FILE_UPLOAD : "api/upload",
  WS_CONNECTION_LOGS: "connection-logs",
  WS_CONNECTION_TOPIC: "/topic/connection-logs",
  WS_PROGRESS_LOGS: "progress-logs",
  WS_PROGRESS_TOPIC: "/topic/progress-logs",

  MOD_ALARMS_REPORT: "MOD Alarms",
  INCIDENTS_REPORT: "Incidents",
  MITIGATIONS_REPORT: "Mitigations",
  PROBLEMATIC_COMPONENTS_REPORT: "Problematic Components",
  PAS_GUIDELINES_REPORT: "PAS Guidelines",
  RECOMMENDATIONS_REPORT: "Recommendations",
  SWAT_REGISTER_REPORT: "SWAT Register",
  CAPACITY_PLANNING_REPORT: "Capacity Planning",
  RCA_REPORT: "RCA",
  INCIDENT_WORKFLOW_REPORT: "Incident Workflow",
  ACRT_REPORT: "ACRT",
  STRING_NA: "NA",
});
